### ISSUE TITLE
Import Error When Following Instructions in WebStorm

### ISSUE THREAD

**Issue by CodeBradley** [glennreyes/fetch-instagram#2]
I created a new project in WebStorm, ran the command `npm install fetch-instagram --save` and once installed I created an index.js file in the root directory of the project and inserted the sample code with my key. When I click "Run index.js", I get the error:

```
C:\Users\User\WebstormProjects\fetch-io\index.js:1
(function (exports, require, module, __filename, __dirname) { import ig from "fetch-instagram";
                                         `                     ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

Process finished with exit code 1
 ```
Command my debug configuration used:
 ```
C:\Program Files\JetBrains\WebStorm 2018.2\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" C:\Users\User\WebstormProjects\fetch-io\index.js
```

Any idea how to get this working? I tried setting up Babel but I'm new to Node/NPM so I'm sure I probably did it wrong.

**Comment by glennreyes** [comment]
Your environment doesn't seem to support ES6 imports, hence also it's not related to this library which builds to cjs.
